language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 6.11.0
  
before_install:
  - npm install -g mocha
  - npm install -g chai

branches:
 only:
   - master
   - developer
script: mocha
