language: node_js

# test on stable and LTS
node_js:
  - "node" #stable
  - "lts/*"
  
before_install:
  - npm install -g mocha
  - npm install -g chai
  - npm install -g nyc

branches:
 only:
   - master
   - developer
script: npm run testcov
